PREFERRED_VERSION_mesa-dri-glsl-native = "8.1.0+git%"
#SRCREV_pn-mesa-dri-glsl-native = "${AUTOREV}"

PREFERRED_VERSION_mesa-dri = "8.1.0+git%"
#SRCREV_pn-mesa-dri = "${AUTOREV}"

PREFERRED_VERSION_libdrm = "2.4.37+git%"
#SRCREV_pn-libdrm = "${AUTOREV}"

PREFERRED_VERSION_wayland-native = "0.95.0"
PREFERRED_VERSION_wayland = "0.95.0"
#SRCREV_pn-wayland = "${AUTOREV}"

PREFERRED_VERSION_weston = "0.95.0"
#SRCREV_pn-wayland = "${AUTOREV}"
